const POPULAR_STOCKS = [
  {id: "AAPL", label: "Apple" },
  {id: "ABBV", label: "AbbVie" },
  {id: "ABT", label: "Abbott Laboratories" },
  {id: "ACN", label: "Accenture" },
  {id: "ADBE", label: "Adobe" },
  {id: "AMD", label: "Advanced Micro Devices" },
  {id: "AMZN", label: "Amazon.com" },
  {id: "ASML", label: "ASML Holding N.V. New York Registry Shares" },
  {id: "AVGO", label: "Broadcom" },
  {id: "BAC", label: "Bank of America" },
  {id: "BRK-B", label: "Berkshire Hathaway" },
  {id: "BSX", label: "Boston Scientific" },
  {id: "COST", label: "Costco Wholesale" },
  {id: "CRM", label: "Salesforce" },
  {id: "CVX", label: "Chevron" },
  {id: "DIS", label: "Walt Disney Company" },
  {id: "GOOG", label: "Alphabet Class C Capital Stock" },
  {id: "HD", label: "Home Depot" },
  {id: "JNJ", label: "Johnson & Johnson" },
  {id: "JPM", label: "JP Morgan Chase" },
  {id: "KO", label: "Coca-Cola Company" },
  {id: "LIN", label: "Linde Ordinary Shares" },
  {id: "LLY", label: "Eli Lilly and Company" },
  {id: "MA", label: "Mastercard Incorporated" },
  {id: "MCD", label: "McDonald's" },
  {id: "META", label: "Meta Platforms" },
  {id: "MRK", label: "Merck & Company" },
  {id: "MSFT", label: "Microsoft" },
  {id: "NFLX", label: "Netflix" },
  {id: "NVDA", label: "NVIDIA" },
  {id: "NVO", label: "Novo Nordisk A/S" },
  {id: "NVS", label: "Novartis AG" },
  {id: "ORCL", label: "Oracle" },
  {id: "PEP", label: "PepsiCo" },
  {id: "PG", label: "Procter & Gamble Company" },
  {id: "SAP", label: "SAP  SE ADS" },
  {id: "SHEL", label: "Shell PLC American Depositary Shares" },
  {id: "TM", label: "Toyota Motor" },
  {id: "TMO", label: "Thermo Fisher Scientific Inc" },
  {id: "TSLA", label: "Tesla" },
  {id: "TSM", label: "Taiwan Semiconductor Manufacturing Company" },
  {id: "UNH", label: "UnitedHealth Incorporated" },
  {id: "V", label: "Visa" },
  {id: "WMT", label: "Walmart" },
  {id: "XOM", label: "Exxon Mobil" },
];

export default POPULAR_STOCKS;
